// Guards the fix for the "no PDF for maintenance" report: the service details
// entered in CompleteServiceModal (supabase/37) actually show up on the printed
// report, per-tenant branding is used instead of a hardcoded name, and user text
// is escaped before it lands in the popup's HTML.
import { describe, it, expect, vi, beforeEach } from "vitest";

vi.mock("@/shared/utils/supabase", () => ({
  supabase: {},
  updateRowStrict: vi.fn(),
  getAccessToken: vi.fn(),
}));

const { generateMaintenancePdf, buildMaintenanceReportModel, pdfFileNameFor } = await import(
  "./maintenancePdf"
);

// generateMaintenancePdf writes into a popup. Capture the HTML instead of opening one.
let html = "";
beforeEach(() => {
  html = "";
  globalThis.window = {
    open: () => ({
      document: {
        write: (h) => {
          html += h;
        },
        close: () => {},
        getElementById: () => null,
      },
      focus: () => {},
      print: () => {},
    }),
  };
});

const completedReq = (extra = {}) => ({
  id: "r1",
  vid: "v1",
  vname: "011 (ABC-123)",
  type: "Brake Service",
  urgency: "urgent",
  uname: "Jordan Crew",
  uid: "u1",
  at: "2026-08-01T12:00:00.000Z",
  notes: "Grinding noise from the front left.",
  status: "completed",
  scheduled_date: "2026-08-03",
  service_type: "Brake Service",
  service_date: "2026-08-05",
  performed_by: "Quick Lube",
  cost: 240.5,
  mileage: 88250,
  wh_notes: "Replaced front pads and rotors.",
  completed_at: "2026-08-05T16:00:00.000Z",
  ...extra,
});

describe("buildMaintenanceReportModel", () => {
  it("reads the service details written by complete_maintenance_service (supabase/37)", () => {
    const m = buildMaintenanceReportModel(completedReq());
    expect(m.serviceType).toBe("Brake Service");
    expect(m.performedBy).toBe("Quick Lube");
    expect(m.cost).toBe(240.5);
    expect(m.mileage).toBe(88250);
  });

  it("degrades gracefully for a ticket completed before supabase/37 ran", () => {
    const legacy = completedReq({
      service_type: null,
      service_date: null,
      performed_by: null,
      cost: null,
      mileage: null,
    });
    const m = buildMaintenanceReportModel(legacy);
    expect(m.serviceType).toBe("");
    expect(m.performedBy).toBe("");
    expect(m.cost).toBeNull();
    expect(m.mileage).toBeNull();
  });

  it("uses the tenant's display name, never a hardcoded company", () => {
    const m = buildMaintenanceReportModel(completedReq(), {
      name: "Legal LLC Name",
      branding: { displayName: "Cedar & Slate" },
    });
    expect(m.companyName).toBe("Cedar & Slate");
  });
});

describe("pdfFileNameFor", () => {
  it("strips punctuation from the vehicle name", () => {
    expect(pdfFileNameFor({ vname: "011 (ABC-123)" })).toBe("MaintenanceReport011ABC123.pdf");
  });

  it("still produces a name with no vehicle on the ticket", () => {
    expect(pdfFileNameFor({})).toBe("MaintenanceReportvehicle.pdf");
  });
});

describe("generateMaintenancePdf", () => {
  it("prints the service details entered when the ticket was completed", () => {
    generateMaintenancePdf(completedReq());
    expect(html).toMatch(/Brake Service/);
    expect(html).toMatch(/Quick Lube/);
    expect(html).toMatch(/240\.50/);
    expect(html).toMatch(/88,250 mi/);
    expect(html).toMatch(/Replaced front pads and rotors/);
  });

  it("omits service fields rather than inventing them for a legacy ticket", () => {
    const legacy = completedReq({
      service_type: null,
      performed_by: null,
      cost: null,
      mileage: null,
    });
    generateMaintenancePdf(legacy);
    expect(html).not.toMatch(/Quick Lube/);
    expect(html).toMatch(/Replaced front pads and rotors/); // wh_notes still shows
  });

  it("escapes ticket text so a crafted note can't inject markup", () => {
    generateMaintenancePdf(completedReq({ notes: "<script>alert(1)</script>" }));
    expect(html).not.toMatch(/<script>alert/);
    expect(html).toMatch(/&lt;script&gt;/);
  });

  it("prefers branding.displayName over the canonical company name", () => {
    generateMaintenancePdf(completedReq(), {
      name: "Legal LLC Name",
      branding: { displayName: "Cedar & Slate" },
    });
    expect(html).toMatch(/CEDAR &amp; SLATE/);
    expect(html).not.toMatch(/LEGAL LLC NAME/);
  });

  it("credits the PRODUCT (Steadwerk) in the footer, not the tenant", () => {
    generateMaintenancePdf(completedReq(), { name: "Sunrise Roofing" });
    expect(html).toMatch(/Generated by Steadwerk/);
    expect(html).not.toMatch(/Generated by Sunrise/);
  });

  it("returns false instead of throwing when the popup is blocked", () => {
    globalThis.window = { open: () => null };
    expect(generateMaintenancePdf(completedReq())).toBe(false);
  });
});
